const FIRST_CHAR = 1;
const FIRST_INDEX = 0;
const HOURS_PER_DAY = 24;
const MINUTES_PER_HOUR = 60;
const SECONDS_PER_MINUTE = 60;

const INIT_DATA_LIFETIME_SECONDS = HOURS_PER_DAY * MINUTES_PER_HOUR * SECONDS_PER_MINUTE;

export { FIRST_CHAR, FIRST_INDEX, INIT_DATA_LIFETIME_SECONDS };
