AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
  - AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members
  CodeDeployRole:
    Type: String
    Description: IAM role to allow AWS CodeDeploy to manage deployment of AWS Lambda functions
  Stage:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: ""

Globals:
  Function:
    AutoPublishAlias: live
    DeploymentPreference:
      Enabled: true
      Type: Canary10Percent5Minutes
      Role: !Ref CodeDeployRole

Resources:
  GetHelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "awscodestar-${ProjectId}-lambda-GetHelloWorld"
      Handler: dist/index.lambda
      Runtime: nodejs12.x
      Timeout: 10
      Environment:
        Variables:
          BOT_KEY: "{{resolve:ssm:BOT_KEY:1}}"
          BOT_USERNAME: "{{resolve:ssm:BOT_USERNAME:1}}"
          BOT_URL: "{{resolve:ssm:BOT_URL:1}}"
          GOOGLE_PROJECT_ID: "{{resolve:ssm:GOOGLE_PROJECT_ID:1}}"
          GOOGLE_CLIENT_EMAIL: "{{resolve:ssm:GOOGLE_CLIENT_EMAIL:1}}"
          GOOGLE_PRIVATE_KEY: "{{resolve:ssm:GOOGLE_PRIVATE_KEY:5}}"
          LOL_TABLE_NAME: !Ref LolTable
          CHAT_SESSION_TABLE_NAME: !Ref ChatSessionTable
          MIKE_APP_URL: "{{resolve:ssm:MIKE_APP_URL:1}}"
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: any
  LambdaExecutionRole:
    Description: Creating service role in IAM for AWS Lambda
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "CodeStar-${ProjectId}-Execution${Stage}"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonPollyFullAccess"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonDynamoDBFullAccess"
  LolTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: lolTable
  ChatSessionTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: chatSession
