const TURN_WINDOW = 100;
const MS_PER_SECOND = 1000;
const MS_PER_MINUTE = 60 * MS_PER_SECOND;
const SENTRY_CONVERSATION_GAP_MS = 10 * MS_PER_MINUTE;

export { SENTRY_CONVERSATION_GAP_MS, TURN_WINDOW };
