const EMPTY_COUNT = 0;
const FIRST_INDEX = 0;
const LAST_FROM_END = -1;
const MS_PER_SECOND = 1000;
const SINGLE_COUNT = 1;

export { EMPTY_COUNT, FIRST_INDEX, LAST_FROM_END, MS_PER_SECOND, SINGLE_COUNT };
